spring:
  application:
    name: product-catalog-service
  cloud:
    config:
       uri: http://SPRING-CLOUD-CONFIG-SERVER
server:
  port: 8080

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,refresh,message
    health:
      show-details: always

fallback:
  default:
    string: N/A

resilience4j:
  circuitbreaker:
    instances:
      getUserService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 30
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
