spring:
  application:
    name: product-catalog-service
server:
  port: 8080

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    web:
      exposure:
        include: health
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      getUserService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 30
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
